config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"
  get "pages/search", to: "pages#search"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end

  def search
    require 'net/http'
    require 'json'
    require 'date'
    @city = params[:search][:city].capitalize
    @url = "https://api.openweathermap.org/data/2.5/weather?q=#{@city}&appid=7cf6bed45018a2fc95b6153aa30917e2"
    @uri = URI(@url)
    @response = Net::HTTP.get(@uri)
    @weather = JSON.parse(@response)

    @country = @weather["sys"]["country"]
    @city = @weather["name"]
    @temp = ((@weather["main"]["temp"].to_f) - 273.15).round(2)
    @feels = ((@weather["main"]["feels_like"]) - 273.15).round(2)
    @hum = @weather["main"]["humidity"]
    @zone = DateTime.strptime(@weather["dt"].to_s,'%s')
    render :home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <%= link_to "WEATHER-APP", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WeatherProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/navigation" %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<div class="row justify-content-center my-4">
  <div class="col-md-12">
    <%= form_with(scope: :search, method: :get, url: pages_search_path) do |f| %>
      <%= f.text_field :city, class: "form-control", id: "exampleFormControlInput1", placeholder: "Enter your city ..." %>
      <div class="text-center">
        <%#= f.submit "Search", class: "btn btn-success my-2" %>
      </div>
    <% end %>
  </div>
</div>

<% if @weather %>
  <div class="row justify-content-center my-4">
    <div class="col-md-3">
      <div class="card">
        <div class="card-body text-center">
          <% if @temp > 5 %>
            <%= image_tag "sun.png", width: 80, height: 80, class: "my-4" %>
          <% elsif @temp > 5 and @temp < 11 %>
            <%= image_tag "cloudy.png", width: 80, height: 80, class: "my-4" %>
          <% elsif @temp > 1 and @temp < 4 %>
            <%= image_tag "raining.png", width: 80, height: 80, class: "my-4" %>
          <% elsif @temp < 0%>
            <%= image_tag "snow.png", width: 80, height: 80, class: "my-4" %>
          <% end %>
          <hr>
          <h6 class="py-2">Country: <span class="text-info"><%= @country %></span></h6>
          <h6 class="py-2">City: <span class="text-info"><%= @city %></span></h6>
          <h6 class="py-2">Temperature: <span class="text-info"><%= @temp %> <sup>o</sup>C</span></h6>
          <h6 class="py-2">Feels Like: <span class="text-info"><%= @feels %> <sup>o</sup>C</span></h6>
          <h6 class="py-2">Humidity: <span class="text-info"><%= @hum %></span></h6>
          <h6 class="py-2">Timezone: <span class="text-info float-left"><%= @zone %></span></h6>
        </div>
      </div>
    </div>
  </div>
<% end %>